pkg: Fix all HTML pages to be XHTML compliant
Ensure that we can parse our pages with ElementTree. This caught a
few actual bugs, like using `<p>` to *close* a paragraph, missing
`</td>`s, or missing `</html>` at the end.

XHTML is stricter than technically necessary (e.g. `<meta>` tags are not
required to get closed), but these rules are somewhat arbitrary. A
proper XML structure is nicer for editors and more robust in browsers.
It will also allow us to e.g. rewrite html2po in Python with etree.

diff --git a/test/static-code b/test/static-code
--- a/test/static-code
+++ b/test/static-code
@@ -83,6 +83,16 @@ test_json_verify() {
     done
 }
 
+test_html_verify() {
+    # Check all HTML files for syntactic validity
+
+    git ls-files -z 'pkg/*.html' | while read -d '' filename; do
+        if ! python3 -c "import xml.etree.ElementTree as ET; ET.parse('${filename}')"; then
+            echo "${filename} contains invalid XML"
+        fi
+    done
+}
+
 test_include_config_h() {
     # Every C file should #include "config.h" at the top
 
