test: Don't update vms on every run
Add option to clean images

diff --git a/test-avocado/run b/test-avocado/run
--- a/test-avocado/run
+++ b/test-avocado/run
@@ -20,6 +20,13 @@
 
 set -e
 
+if [ -z "$LIBVIRT_DEFAULT_URI" ]; then
+    LIBVIRT_DEFAULT_URI="qemu:///system"
+fi
+export LIBVIRT_DEFAULT_URI
+
+export LIBGUESTFS_BACKEND=direct
+
 cd "`dirname "$0"`"
 
 source ./lib/host_setup.sh
@@ -27,6 +34,10 @@ source ./lib/create_test_machine.sh
 LUSER=`whoami`
 ENV_VARIABLES=./lib/var.env
 rm -f $ENV_VARIABLES
+
+if [ -z "$TESTS_TIMEOUT" ]; then
+    TESTS_TIMEOUT="15m"
+fi
 
 # setup enviromental variable to override these values (useful for testing on another environment)
 # GUEST_NUMBER , GUESTOS
@@ -50,7 +61,7 @@ fi
 echolog ">>> $GUESTOS testing <<<"
 
 if check_host $LUSER; then
-    echolog "Host already configured"
+    echodebug "Host already configured"
 else
     if sudo ./lib/host_setup.sh $LUSER; then
         echolog "Host environment ready"
@@ -65,33 +76,81 @@ if [ ! -e ~/.ssh/id_rsa ]; then
     ssh-keygen -q -f ~/.ssh/id_rsa -N "" </dev/null
 fi
 
+GUESTNAME="checkmachine${GUEST_NUMBER}"
+GUEST1=`vm_get_name $GUESTNAME $GUESTOS`
+IPA_DISTRO=fedora-21
+GUEST_IPA=`vm_get_name ipa $IPA_DISTRO`
+
+# TODO: allow setting this up in a parallel environment for testing
+# and migrate to the "real" pool once it works
+if [ -n "$CLEAN" ]; then
+    echolog "Delete network"
+    virsh net-destroy $HS_POOLNAME || true
+    virsh net-undefine $HS_POOLNAME || true
+
+    echolog "Delete $GUEST1"
+    virsh destroy $GUEST1 &>/dev/null || true
+    virsh snapshot-delete $GUEST1 initialized &>/dev/null || true
+    virsh undefine $GUEST1 &>/dev/null || true
+    virsh vol-delete --pool $HS_POOLNAME $GUEST1.qcow2 &>/dev/null || true
+
+    echolog "Delete $GUEST_IPA"
+    virsh destroy $GUEST_IPA &>/dev/null || true
+    virsh snapshot-delete $GUEST_IPA initialized &>/dev/null || true
+    virsh undefine $GUEST_IPA &>/dev/null || true
+    virsh vol-delete --pool $HS_POOLNAME $GUEST_IPA.qcow2 &>/dev/null || true
+
+    definenet $HS_POOLNAME
+    virsh net-start $HS_POOLNAME
+    virsh net-autostart $HS_POOLNAME
+    vm_create $GUESTNAME $GUESTOS
+    vm_create ipa $IPA_DISTRO
+fi
+
+# make sure all machines are shutdown to avoid residual interaction
+echolog "Ensure no machines are running"
+virsh destroy $GUEST1 &>/dev/null || true
+virsh destroy $GUEST_IPA &>/dev/null || true
+
 # GUEST1 machine
 #
-GUESTNAME="checkmachine${GUEST_NUMBER}"
-vm_create $GUESTNAME $GUESTOS
-GUEST1=`vm_get_name $GUESTNAME $GUESTOS`
-
-if virsh -c qemu:///system snapshot-info $GUEST1 initialized &>/dev/null; then
-    echolog "Reverting $GUEST1 to last 'initialized' state"
-    virsh -c qemu:///system snapshot-revert $GUEST1 initialized >/dev/null
-    virsh -c qemu:///system snapshot-delete $GUEST1 initialized >/dev/null
+if virsh snapshot-info $GUEST1 initialized &>/dev/null; then
+    echolog "Revert $GUEST1 to last 'initialized' state"
+    virsh snapshot-revert $GUEST1 initialized >/dev/null
+else
+    echolog "Set up $GUEST1"
+    vm_ssh $GUEST1 date --set $(date -Ins) >/dev/null
+    vm_ssh $GUEST1 bash -c "cat - >/tmp/cockpit.spec" <../tools/cockpit.spec
+    vm_ssh $GUEST1 bash -s < ./lib/guest-cockpit-$METHOD.sh /tmp/cockpit.spec
+    echolog "Save $GUEST1 'initialized' state"
+    virsh snapshot-create-as $GUEST1 initialized >/dev/null
 fi
-echolog "Setting up $GUEST1"
-vm_ssh $GUEST1 date --set $(date -Ins) >/dev/null
-vm_ssh $GUEST1 bash -c "cat - >/tmp/cockpit.spec" <../tools/cockpit.spec
-vm_ssh $GUEST1 bash -s < ./lib/guest-cockpit-$METHOD.sh /tmp/cockpit.spec
-echolog "Saving $GUEST1 'initialized' state"
-virsh -c qemu:///system snapshot-create-as $GUEST1 initialized >/dev/null
 
 # GUEST_IPA machine
 #
-IPA_DISTRO=fedora-21
-vm_create ipa $IPA_DISTRO
-GUEST_IPA=`vm_get_name ipa $IPA_DISTRO`
+if virsh snapshot-info $GUEST_IPA initialized &>/dev/null; then
+    echolog "Revert $GUEST_IPA to last 'initialized' state"
+    virsh snapshot-revert $GUEST_IPA initialized >/dev/null
+else
+    echolog "Set up $GUEST_IPA"
+    vm_ssh $GUEST_IPA date --set $(date -Ins) >/dev/null
+    vm_ssh $GUEST_IPA bash -s < ./lib/guest-ipa.sh
+    echolog "Save $GUEST_IPA 'initialized' state"
+    virsh snapshot-create-as $GUEST_IPA initialized >/dev/null
+fi
 
-echolog "Setting up $GUEST_IPA"
-vm_ssh $GUEST_IPA date --set $(date -Ins) >/dev/null
-vm_ssh $GUEST_IPA bash -s < ./lib/guest-ipa.sh
+for MACHINE in $GUEST1 $GUEST_IPA
+do
+	  if ! vm_wait_online $MACHINE; then
+        echolog "FAILED waiting for $MACHINE to be online"
+        exit 1
+    fi
+done
+
+if [ -n "$SKIP_TEST" ]; then
+    exit 0
+fi
+
 
 # Write variables for IPA tests
 echo "IPADOMAIN='cockpit.lan'" >> $ENV_VARIABLES
@@ -103,7 +162,9 @@ write_out $GUEST_IPA
 echo
 
 LOCAL_VERSION=`avocado -v 2>&1 |grep Avo`
-REMOTE_VERSION=`vm_ssh $GUEST1 "avocado -v " 2>&1 | grep Avo`
+echolog "getting remote version"
+#REMOTE_VERSION=`vm_ssh $GUEST1 "avocado -v " 2>&1 | grep Avo`
+REMOTE_VERSION=`vm_ssh $GUEST1 "avocado -v " | grep Avo`
 if [ "$LOCAL_VERSION" != "$REMOTE_VERSION" ]; then
     echolog "avocado versions are not same on LOCAL and REMOTE $LOCAL_VERSION != $REMOTE_VERSION (SHOULD BE)"
     exit 11
@@ -111,6 +172,7 @@ fi
 
 # Install cockpit sources to $GUEST1
 #
+echolog "installing cockpit sourcecode"
 ( cd $(git rev-parse --show-toplevel) && git archive HEAD --prefix cockpit/ ) \
   | vm_ssh $GUEST1 "rm -rf /root/cockpit && tar xfm - --directory /root/"
 
@@ -128,4 +190,10 @@ else
     	AVOCADO_TESTS="$COMPILE_TEST $AVOCADO_TESTS";
     fi
 fi
-avocado run $AVOCADO_PARAMS $AVOCADO_TESTS
+echolog "run tests"
+# Make sure the tests don't stall
+timeout $TESTS_TIMEOUT avocado run $AVOCADO_PARAMS $AVOCADO_TESTS || true
+
+# Clean up after ourselves
+virsh destroy $GUEST1 || true
+virsh destroy $GUEST_IPA || true
