tls: Fix auto-renewal of FreeIPA issued ws certificates
With the previous SELinux permission fix for /etc/cockpit/ws-certs.d/,
ipa-getcert can now also write the cockpit certificate, instead of just
a temporary file. This makes auto-renewal actually work on most
operating systems other than RHEL 8 (which does not use our own SELinux
policy yet); on the latter, fall back to the old method of manually
copying the certificate. Check both cases more carefully in the tests.

Also fix the certificate cleanup to give the full path for either case
-- we don't want this to remove *any* "10-ipa" certificate (other
projects or admins might happen to use that as well).

diff --git a/src/tls/cockpit-certificate-helper.in b/src/tls/cockpit-certificate-helper.in
--- a/src/tls/cockpit-certificate-helper.in
+++ b/src/tls/cockpit-certificate-helper.in
@@ -108,23 +108,30 @@ cmd_ipa_request() {
     klist -k "${KEYTAB}" | grep -qF "${SERVICE}" || \
         ipa-getkeytab -p "HTTP/${HOST}" -k "${KEYTAB}"
 
-    # request the certificate (into the working directory)
-    ipa-getcert request -f 10-ipa.cert -k 10-ipa.key -K "HTTP/${HOST}" -w -v
-
-    # install it into /etc
-    install_cert 10-ipa.cert
-    install_key 10-ipa.key
+    # request the certificate and put it into our certificate directory
+    if ! selinuxenabled || [ "$(stat -c %C /etc/cockpit/ws-certs.d/ | cut -f3 -d:)" = cert_t ]; then
+        # the prefered way is to let certmonger write the certificate directly, so that auto-refresh works
+        ipa-getcert request -f "${COCKPIT_WS_CERTS_D}/10-ipa.cert" -k "${COCKPIT_WS_CERTS_D}/10-ipa.key" -K "HTTP/${HOST}" -m 640 -o root:${COCKPIT_GROUP:-root} -M 644 -w -v
+    else
+        # ... but that does not work on RHEL 8 or customized SELinux policies, so copy it ourselves
+        # request the certificate (into the working directory)
+        ipa-getcert request -f 10-ipa.cert -k 10-ipa.key -K "HTTP/${HOST}" -w -v
+        # install it into /etc
+        install_cert 10-ipa.cert
+        install_key 10-ipa.key
+    fi
 }
 
 cmd_ipa_cleanup() {
-        # clean up keytab
-        if [ -e "${KEYTAB}" ]; then
-            ipa-rmkeytab -k "${KEYTAB}" -p "${SERVICE}"
-        fi
+    # clean up keytab
+    if [ -e "${KEYTAB}" ]; then
+        ipa-rmkeytab -k "${KEYTAB}" -p "${SERVICE}"
+    fi
 
-        # clean up certificate
-        ipa-getcert stop-tracking -f 10-ipa.cert -k 10-ipa.key
-        rm "${COCKPIT_WS_CERTS_D}/10-ipa.cert" "${COCKPIT_WS_CERTS_D}/10-ipa.key"
+    # clean up certificate; support both "copy" and "direct" modes from cmd_ipa_request()
+    rm "${COCKPIT_WS_CERTS_D}/10-ipa.cert" "${COCKPIT_WS_CERTS_D}/10-ipa.key"
+    ipa-getcert stop-tracking -f "${COCKPIT_WS_CERTS_D}/10-ipa.cert" -k "${COCKPIT_WS_CERTS_D}/10-ipa.key" || \
+        ipa-getcert stop-tracking -f /run/cockpit/certificate-helper/10-ipa.cert -k /run/cockpit/certificate-helper/10-ipa.key
 }
 
 cmd_ipa() {
