tls: Don't overwrite an existing TLS key if the cert is missing
This is an unusual situation -- likely, the admin tried to manually
replace the certificate and did something wrong. We should not silently
regenerate everything then, but instead give an useful errror message.

This makes it more symmetric to removing the key but keeping the cert
(which also errors out instead of silently regenerating).

See https://github.com/cockpit-project/cockpit/pull/21069#issuecomment-2540659336

Closes #21069

diff --git a/src/tls/cockpit-certificate-helper.in b/src/tls/cockpit-certificate-helper.in
--- a/src/tls/cockpit-certificate-helper.in
+++ b/src/tls/cockpit-certificate-helper.in
@@ -76,6 +76,12 @@ cmd_selfsign() {
     local KEYFILE="0-self-signed.key"
     local CA_FILE="0-self-signed-ca.pem"
 
+    # do not stomp over a partial key -- the admin tried to do something wrong
+    if [ -e "${COCKPIT_WS_CERTS_D}/${KEYFILE}" ] && [ ! -e "${COCKPIT_WS_CERTS_D}/${CERTFILE}" ]; then
+        echo "Error: Found $KEYFILE but no $CERTFILE. Please remove the key file first." >&2
+        exit 1
+    fi
+
     mkdir -pZ "$COCKPIT_WS_CERTS_D"
 
     # We renew certificates up to 30 days before expiry, so give ourselves a
