test: Use make-srpm from our repo instead of bots
bots' make-srpm script is specific to cockpit. Let's deprecate and
eventually remove it. starter-kit based projects have their own
`make sprm`.

Copy the bots code into our own tools/make-srpm, and upload that to the
VM during image-prepare.

This makes it easier to modify srpm building in the future without
having to do coordinated changes across two repos or branches, and
avoids cockpit specific stuff in bots.

diff --git a/tools/make-srpm b/tools/make-srpm
--- a/tools/make-srpm
+++ b/tools/make-srpm
@@ -38,4 +38,30 @@ else
     source="$1"
 fi
 
-exec "$base/bots/images/scripts/lib/make-srpm" "$source"
+version=$(echo "$source" | sed -n 's|.*cockpit-\([^ /-]\+\)\.tar\..*|\1|p')
+if [ -z "$version" ]; then
+    echo "make-srpm: couldn't parse version from tarball: $source"
+    exit 2
+fi
+
+# We actually modify the spec so that the srpm is standalone buildable
+modify_spec() {
+sed -e "/^Version:.*/d" -e "1i\
+%define wip wip\nVersion: $version\n"
+}
+
+tmpdir=$(mktemp -d $PWD/srpm-build.XXXXXX)
+tar xaf "$source" -O cockpit-$version/tools/cockpit.spec | modify_spec > $tmpdir/cockpit.spec
+
+rpmbuild -bs \
+         --quiet \
+         --define "_sourcedir $(dirname $source)" \
+         --define "_specdir $tmpdir" \
+         --define "_builddir $tmpdir" \
+         --define "_srcrpmdir `pwd`" \
+         --define "_rpmdir $tmpdir" \
+         --define "_buildrootdir $tmpdir/.build" \
+         $tmpdir/cockpit.spec
+
+rpm --qf '%{Name}-%{Version}-%{Release}.src.rpm\n' -q --specfile $tmpdir/cockpit.spec | head -n1
+rm -rf $tmpdir
