build: Consistently include config.h
A lot of files were missing it. That file defines `_GNU_SOURCE` and
other global macros (via `AC_USE_SYSTEM_EXTENSIONS`), which we want to
apply to all files.

Add a new test-static-code check to detect .c files which are missing
config.h, add it to the missing files, and reformat the others to abide
to the strict requirement of that test: it now needs to be the first
macro. Drop the obsolete `HAVE_CONFIG_H`, and also drop the now
redundant definitions of `_GNU_SOURCE` in the .c files.

Also drop the global `-D_POSIX_PTHREAD_SEMANTICS`, as it's part of
`AC_USE_SYSTEM_EXTENSIONS`.

diff --git a/tools/test-static-code b/tools/test-static-code
--- a/tools/test-static-code
+++ b/tools/test-static-code
@@ -2,7 +2,7 @@
 # run static code checks like pyflakes and pycodestyle
 set -eu
 
-echo "1..8"
+echo "1..9"
 
 cd "${srcdir:-.}"
 fail=0
@@ -143,6 +143,20 @@ elif V=0 tools/node-modules test_static_code; then
 else
     echo "not ok 8 node_modules freshness"
     fail=1
+fi
+
+# for every C file, if there is any line starting with '#', then the first one
+# must be exactly: #include "config.h"
+if [ -e .git ]; then
+    for f in $(git ls-tree --name-only -r --full-name HEAD | grep '\.c$'); do
+        if sed -n '/^#include "config.h"$/ q1; /^\s*#/ q0' "$f"; then
+            echo "$f"
+            fail=1
+        fi
+    done
+    echo "$([ $fail -eq 0 ] || echo 'not ')ok 9 config.h properly included from all files"
+else
+    echo "ok 9 config.h # SKIP not a git tree"
 fi
 
 exit $fail
