tools: Properly munge the patternfly font paths
The OpenSans fonts are in our static directory and used on the
login page. These are not part of a package. In addition we don't
ship any other font formats but woff.

The patternfly.sed script munges patternfly for our use cases,
however it wasn't working with the new patternfly.

Update the script and add tests.

Closes #7823

diff --git a/tools/test-static-code b/tools/test-static-code
--- a/tools/test-static-code
+++ b/tools/test-static-code
@@ -2,8 +2,9 @@
 # run static code checks like pyflakes and pep8
 set -eu
 
-echo "1..4"
+echo "1..5"
 
+builddir=$(pwd)
 cd "${srcdir:-.}"
 fail=0
 
@@ -78,6 +79,18 @@ if [ $safe == "no" ]; then
    fail=1
 else
     echo "ok 4 unsafe-security-policy"
+fi
+
+#
+# Bad paths or modifications in patternfly for fonts
+#
+
+if grep "\.\./fonts/OpenSans\|fonts/.*eot\|truetype" dist/*/*.css $builddir/dist/*/*.css >&2; then
+    echo "ERROR: invalid patternfly fonts paths found" >&2
+    echo "not ok 5 patternfly-font-paths"
+    fail=1
+else
+    echo "ok 5 patternfly-font-paths"
 fi
 
 exit $fail
