FIXUP: Fix grep and TAP protocol
 - Check *.css file in srcdir (they are part of "make dist"), not (only)
   in the build dir (that only has *.css.gz)
 - Don't use grep -R, we already specify the file paths that we want to check
 - Send ERROR message to stderr, to avoid confusing the TAP protocol

diff --git a/tools/test-static-code b/tools/test-static-code
--- a/tools/test-static-code
+++ b/tools/test-static-code
@@ -4,7 +4,7 @@ set -eu
 
 echo "1..5"
 
-distdir=$(pwd)
+builddir=$(pwd)
 cd "${srcdir:-.}"
 fail=0
 
@@ -85,8 +85,8 @@ fi
 # Bad paths or modifications in patternfly for fonts
 #
 
-if grep -R "\.\./fonts/OpenSans\|fonts/.*eot\|truetype" $distdir/dist/*/*.css >&2; then
-    echo "ERROR: invalid patternfly fonts paths found"
+if grep "\.\./fonts/OpenSans\|fonts/.*eot\|truetype" dist/*/*.css $builddir/dist/*/*.css >&2; then
+    echo "ERROR: invalid patternfly fonts paths found" >&2
     echo "not ok 5 patternfly-font-paths"
     fail=1
 else
