Replace translatable html attribute with translate which is valid
translatable is not a valid html attribute and was creating a lot of
noise in html validators.

Closes #13133

diff --git a/tools/test-static-code b/tools/test-static-code
--- a/tools/test-static-code
+++ b/tools/test-static-code
@@ -50,6 +50,11 @@ if out=$(find src/ pkg/ -name '*.js' -o -name '*.jsx' | xargs grep -n -E "(gette
     echo "$out" >&2
     echo "not ok 3 js-translatable-strings"
     fail=1
+elif out=$(grep -r 'translatable=["'\'']yes' pkg/ doc/); then
+    echo "ERROR: 'translatable' HTML attribute is invalid, use 'translate' instead"
+    echo "$out" >&2
+    echo "not ok 3 js-translatable-strings"
+    fail=1
 else
     echo "ok 3 js-translatable-strings"
 fi
