webpack-jumpstart: add --partial mode
Add an option to webpack-jumpstart to permit jumpstarting even with
non-trivial local changes (committed or not) in the working tree.

We deal with any potential conflicts by touching changed files after
unpacking dist/, forcing any impacted packages to be rebuilt.  That
might end up touching some .c files or other files that have nothing to
do with dist/, but it's cleaner than trying to deal with this manually,
and rebuilding C is fast.

We also anticipate that it might be desirable to mix --partial and
--rebase, and even add an --autostash to our rebase call to ensure that
this is possible.

diff --git a/tools/webpack-jumpstart b/tools/webpack-jumpstart
--- a/tools/webpack-jumpstart
+++ b/tools/webpack-jumpstart
@@ -19,12 +19,15 @@ cd "$(realpath -m "$0"/../..)"
 
 wait=''
 rebase=''
+partial=''
 while [ $# != 0 ] ; do
     case "$1" in
         --wait)
             wait=1;;
         --rebase)
             rebase=1;;
+        --partial)
+            partial=1;;
         *)
             echo "usage: $0 [--rebase] [--wait]" >&2
             exit 1
@@ -47,20 +50,23 @@ fi
 # Here we find "base commit": the commit in our local tree which is equal to
 # the HEAD of the PR at the time the jumpstart was built.  This might not be
 # the commit that the jumpstart was actually built against (in case the PR
-# wasn't fully-rebased and GitHub merged some commits from main).
-# --rebase helps us deal with those situations.
+# wasn't fully-rebased and GitHub merged some commits from main) and it might
+# also not be the current local HEAD (in case local changes were added after.
+# --rebase and --partial help us deal with those situations.
 #
 # For example:
 #
+#                        o---L---l           (local tree at start)
+#                       /
 #              a---b---H                     (PR head)
 #             /        |\
 #            /       --M \---N               (GitHub PR merge commits)
 #           /       /       /
 #   ---o---o---o---m---o---n                 (origin/main)
 #                   \
-#                    a'--b'--H'              (rebased result)
+#                    a'--b'--H'--L'--l'      (rebased result)
 #
-# We might be run from H, M, or N.
+# We might be run from H, M, N, L or l.
 #
 # Someone has proposed a PR with three commits ('a', 'b', and head 'H'),
 # branched off of main, which had two additional commits (up to head 'm') at
@@ -77,19 +83,43 @@ fi
 # merge commit ('N') in case main received additional commits.  In either case,
 # the best thing we can do in either case is to back up to the original head
 # 'H' and rebase onto 'm' from there, as above.
+#
+# Finally, it might be that our local tree was originally based on the HEAD
+# commit that was built for the jumpstart, but has additionally gained extra
+# local commits (head 'L') and/or uncommitted changes ('l').  In this case, we
+# need to search through our own history to find the latest commit for which a
+# jumpstart was built (ie: 'H'), and then after applying that jumpstart, touch
+# the files that were changed, in order to make sure everything is properly
+# rebuilt.  That's --partial.
 
-if [ -n "$(git status --porcelain)" ]; then
-    echo 'Refusing operation on an unclean tree' >&2
-    echo
-    git status >&2
-    exit 1
+if test -n "${partial}"; then
+    tag=""
+    # fetch the available commits, then iterate our history looking for the first match
+    available="$(git_cache ls-remote origin 'refs/tags/sha-*' | cut -f2 -d-)"
+    for commit in $(git log -n 100 --format=%H); do
+        if [ "${available%${commit}*}" != "${available}" ]; then
+            tag="sha-${commit}"
+            break
+        fi
+    done
+    if [ -z "${tag}" ]; then
+        echo "Unable to find any suitable commit" >&2
+        exit 1
+    fi
+else
+    if [ -n "$(git status --porcelain)" ]; then
+        echo 'Refusing operation on an unclean tree: try --partial' >&2
+        echo
+        git status >&2
+        exit 1
+    fi
+    # If we are rebasing and the HEAD commit is a merge, reset to the
+    # merged commit before proceeding.
+    if test -n "${rebase}" && git rev-parse --verify HEAD^2 >/dev/null; then
+        git reset --hard HEAD^2
+    fi
+    tag="sha-$(git rev-parse HEAD)"
 fi
-# If we are rebasing and the HEAD commit is a merge, reset to the
-# merged commit before proceeding.
-if test -n "${rebase}" && git rev-parse --verify HEAD^2 >/dev/null; then
-    git reset --hard HEAD^2
-fi
-tag="sha-$(git rev-parse HEAD)"
 
 for try in $(seq 50 -1 0); do
     if fetch_to_cache tag "${tag}"; then
@@ -110,12 +140,12 @@ if [ -n "${rebase}" ]; then
         message FETCH ".  [${merge_base}]"
         git fetch --no-write-fetch-head origin "${merge_base}"
     fi
-    git rebase -- "${merge_base}"
+    git rebase --autostash -- "${merge_base}"
 fi
 
 target_tree="$(cat_from_cache "${tag}" tree)"
 changed_files="$(git diff --name-only "${target_tree}")"
-if [ -n "${changed_files}" ]; then
+if [ -n "${changed_files}" -a -z "${partial}" ]; then
     if [ -n "${rebase-}" ]; then
         echo "Internal error: even after rebase, don't have the correct tree" >&2
     else
@@ -126,3 +156,8 @@ fi
 
 tools/node-modules make_package_lock_json
 unpack_from_cache "${tag}"
+
+if [ -n "${changed_files}" ]; then
+    printf "\nTouching the following changed files:\n%s\n\n" "${changed_files}" >&2
+    touch -- ${changed_files}
+fi
