tools: Ignore PhantomJS crashes in Debian avocado autopkgtest
checklogin-basic.py causes a PhantomJS crash on Ubuntu artful on amd64
which does not reproduce in QEMU. That's not a reason to block cockpit,
so ignore these.

Bug: https://bugs.debian.org/873241

diff --git a/tools/debian/tests/avocado b/tools/debian/tests/avocado
--- a/tools/debian/tests/avocado
+++ b/tools/debian/tests/avocado
@@ -17,4 +17,10 @@ pip install avocado-framework
 npm install sizzle
 
 test/avocado/checklogin-raw.py
-test/avocado/checklogin-basic.py
+if ! test/avocado/checklogin-basic.py; then
+    if grep -q 'Error: PhantomJS or driver broken' /tmp/avocado*core.job*/job.log; then
+        echo "Ignoring PhantomJS failure"
+    else
+        exit 1
+    fi
+fi
